### ISSUE TITLE
不太懂 求解

### ISSUE THREAD

**Issue by xiaofengv233** [exqlnet/chaoxing_sign#1]
![屏幕截图(1)](https://user-images.githubusercontent.com/24617660/111058173-92221e80-84c7-11eb-9fd7-d9e683440660.png)

**Comment by exqlnet** [comment]
抱歉，原因是没有安装依赖
因为之前把依赖直接放在目录里的，删掉之后我忘记把依赖安装的命令放入到镜像构建里去了
现在已经修复了

**Comment by xiaofengv233** [comment]
> 抱歉，原因是没有安装依赖
> 因为之前把依赖直接放在目录里的，删掉之后我忘记把依赖安装的命令放入到镜像构建里去了
> 现在已经修复了

好的
