### ISSUE TITLE
云函数调用失败 求解

### ISSUE THREAD

**Issue by xiaofengv233** [exqlnet/chaoxing_sign#2]
日志:

ERROR RequestId:e563c248-acbd-4dc1-9315-3990536cd3ad Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/redis/connection.py\", line 585, in _connect\n    socket.SOCK_STREAM):\n  File \"/var/lang/python3/lib/python3.6/socket.py\", line 743, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -2] Name or service not known\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 176, in handle\n    ret = self.real_handler(event, context)\n  File \"/var/user/cx_tx_scf.py\", line 15, in main_handler\n    s = AutoSign(username, password, server_chan_key, redis_host=\"\u003credis-host\u003e\", redis_port=6379)\n  File \"/var/user/cx.py\", line 31, in __init__\n    if not self.check_cookies_status():\n  File \"/var/user/cx.py\", line 45, in check_cookies_status\n    cookies_byte = self.cache.get(self.username + \"_cookies\")\n  File \"/var/user/redis/client.py\", line 1606, in get\n    return self.execute_command('GET', name)\n  File \"/var/user/redis/client.py\", line 898, in execute_command\n    conn = self.connection or pool.get_connection(command_name, **options)\n  File \"/var/user/redis/connection.py\", line 1192, in get_connection\n    connection.connect()\n  File \"/var/user/redis/connection.py\", line 563, in connect\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error -2 connecting to \u003credis-host\u003e:6379. Name or service not known.","statusCode":430}

Report RequestId:e563c248-acbd-4dc1-9315-3990536cd3ad Duration:71ms Memory:512MB MemUsage:23.976562MB

**Comment by exqlnet** [comment]
请仔细阅读 `README.md`
