### ISSUE TITLE
前端源代码可以给一下吗

### ISSUE THREAD

**Issue by xiao-baii** [exqlnet/chaoxing_sign#4]

**Comment by exqlnet** [comment]
已上传，开了个新的仓库，前端是个非常简单的Vue项目

[exqlnet/chaoxing_sign_fe](https://github.com/exqlnet/chaoxing_sign_fe)

**Comment by xiao-baii** [comment]
好的非常感谢，学习了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "exqlnet/chaoxing_sign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [exqlnet/chaoxing_sign] 前端源代码可以给一下吗 (#4)





 
已上传，开了个新的仓库，前端是个非常简单的Vue项目
 
exqlnet/chaoxing_sign_fe
